import Head from "next/head";
import styles from "@/src/styles/Home.module.css";
import Layout from "../components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/profile-picnew.png";
import profilePicc from "../../public/images/profile/profile-picnow.png";
import AnimateText from "../components/AnimateText";
import Link from "next/link";
import { LinkArrow } from "../components/Icons";
import HireMe from "../components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "../components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
        <Layout className="pt-0 md:pt-16 sm:pt-8 ">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-[45%] md:w-full">
              <Image
                src={profilePicc}
                alt="Jhonn"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                 (max-width: 1200px) 50vw,
                 50vw"
              />
            </div>
            <div className="w-[54%] flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimateText
                text="Convirtiendo las ideas en realidad con código y diseño."
                className="!text-6xl !text-left dark:text-light 
                xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl xs:mt-6 "
              />

              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Como desarrollador full-stack, me dedico a convertir ideas en
                aplicaciones web innovadoras. Explore mis últimos proyectos y
                artículos, mostrando mi experiencia en diversas tecnologías de
                desarrollo web.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center ">
                <Link
                  href="/CV_JhonnDiaz_ES.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark duration-300 dark:bg-light dark:text-dark 
                  hover:dark:bg-dark hover:dark:text-light hover:dark:border-light sm:px-2  md:text-sm   "
                  download={true}
                >
                  Descargar CV
                  <LinkArrow className=" ml-3 " />
                </Link>
                <Link
                  href="mailto:jhonndiaz58@gmail.com"
                  target={"_blank"}
                  className=" text-dark p-2.5 rounded-lg px-6 text-lg hover:text-dark 
                   border-2 border-solid border-transparent hover:border-dark ml-4 font-medium 
                   capitalize underline hover:dark:border-light dark:text-light sm:ml-1 md:text-base "
                >
                  Contacto
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}

{
  /* <a
  target="_blank"
  class="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark duration-300 dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base  "
  download=""
  href="/CV_Antonio_Rodr%C3%ADguez.pdf"
>
  Descargar CV
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    class="w-6 ml-2 xs:w-7"
  >
    <g fill="none">
      <path d="M24 0v24H0V0h24ZM12.593 23.258l-.011.002-.071.035-.02.004-.014-.004-.071-.035c-.01-.004-.019-.001-.024.005l-.004.01-.017.428.005.02.01.013.104.074.015.004.012-.004.104-.074.012-.016.004-.017-.017-.427c-.002-.01-.009-.017-.017-.018Zm.265-.113-.013.002-.185.093-.01.01-.003.011.018.43.005.012.008.007.201.093c.012.004.023 0 .029-.008l.004-.014-.034-.614c-.003-.012-.01-.02-.02-.022Zm-.715.002a.023.023 0 0 0-.027.006l-.006.014-.034.614c0 .012.007.02.017.024l.015-.002.201-.093.01-.008.004-.011.017-.43-.003-.012-.01-.01-.184-.092Z"></path>
      <path
        fill="currentColor"
        d="M8 5v2H5v13h14V7h-3V5h3a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h3Zm4-3a1 1 0 0 1 1 1v10.828L14.828 12a1 1 0 1 1 1.415 1.414l-3.36 3.359a1.25 1.25 0 0 1-1.767 0l-3.359-3.359A1 1 0 1 1 9.172 12L11 13.828V3a1 1 0 0 1 1-1Z"
      ></path>
    </g>
  </svg>
</a>; */
}
